# Generated by Django 5.1.6 on 2025-04-01 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=1)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Record',
                'verbose_name_plural': 'Progress Records',
                'ordering': ['-last_accessed'],
                'constraints': [models.CheckConstraint(condition=models.Q(('completed_lessons__lte', models.F('total_lessons'))), name='completed_lessons_lte_total_lessons'), models.CheckConstraint(condition=models.Q(('total_lessons__gte', 1)), name='total_lessons_gte_1')],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
