# Generated by Django 5.1.6 on 2025-04-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20250404_1259'),
    ]

    operations = [
    ]
